# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
# a variable group
- group: kvault-vars
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
  - task: CmdLine@2
    displayName: Terraform Init
    inputs:
      script: >
        terraform init -backend-config="access_key=$(kv-terradom01-key1)"
      workingDirectory: terraform
  - task: CmdLine@2
    displayName: Terraform Validate
    inputs:
      script: >+
        terraform validate
      workingDirectory: terraform
  - task: CmdLine@2
    displayName: Terraform Plan
    inputs:
      script: >+
        terraform plan -input=false -out=tfplan -var="kv-admin-user-password=$(kv-admin-user-password)" -var="kv-ado-spn-appid=$(kv-ado-spn-appid)" -var="kv-ado-spn-password=$(kv-ado-spn-password)" -var="kv-ado-spn-tenant=$(kv-ado-spn-tenant)"
      workingDirectory: terraform
  - task: CmdLine@2
    displayName: Terraform Destroy
    inputs:
      script: >+
        terraform destroy -auto-approve -input=false -var="kv-admin-user-password=$(kv-admin-user-password)" -var="kv-ado-spn-appid=$(kv-ado-spn-appid)" -var="kv-ado-spn-password=$(kv-ado-spn-password)" -var="kv-ado-spn-tenant=$(kv-ado-spn-tenant)"
      workingDirectory: terraform