USE [master]
GO
/****** Object: Database [secretserver] Script Date: 4/30/2021 10:24:33 AM ******/
CREATE DATABASE [secretserver]
CONTAINMENT = NONE
ON PRIMARY 
( NAME = N'secretserver', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\secretserver.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
LOG ON 
( NAME = N'secretserver_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\secretserver_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [secretserver] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [secretserver].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [secretserver] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [secretserver] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [secretserver] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [secretserver] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [secretserver] SET ARITHABORT OFF 
GO
ALTER DATABASE [secretserver] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [secretserver] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [secretserver] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [secretserver] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [secretserver] SET CURSOR_DEFAULT GLOBAL 
GO
ALTER DATABASE [secretserver] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [secretserver] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [secretserver] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [secretserver] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [secretserver] SET DISABLE_BROKER 
GO
ALTER DATABASE [secretserver] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [secretserver] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [secretserver] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [secretserver] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [secretserver] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [secretserver] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [secretserver] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [secretserver] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [secretserver] SET MULTI_USER 
GO
ALTER DATABASE [secretserver] SET PAGE_VERIFY CHECKSUM 
GO
ALTER DATABASE [secretserver] SET DB_CHAINING OFF 
GO
ALTER DATABASE [secretserver] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [secretserver] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [secretserver] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [secretserver] SET ACCELERATED_DATABASE_RECOVERY = OFF 
GO
ALTER DATABASE [secretserver] SET QUERY_STORE = OFF
GO
ALTER DATABASE [secretserver] SET READ_WRITE 
GO
USE [master]
GO
/* For security reasons the login is created disabled and with a random password. */
/****** Object: Login [secretadmin] Script Date: 4/30/2021 10:25:13 AM ******/
CREATE LOGIN [secretadmin] WITH PASSWORD=N'#{kv-win-admin-password}#', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER LOGIN [secretadmin] DISABLE
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [secretadmin]
GO
ALTER SERVER ROLE [securityadmin] ADD MEMBER [secretadmin]
GO
ALTER SERVER ROLE [serveradmin] ADD MEMBER [secretadmin]
GO
ALTER SERVER ROLE [setupadmin] ADD MEMBER [secretadmin]
GO
ALTER SERVER ROLE [processadmin] ADD MEMBER [secretadmin]
GO
ALTER SERVER ROLE [diskadmin] ADD MEMBER [secretadmin]
GO
ALTER SERVER ROLE [dbcreator] ADD MEMBER [secretadmin]
GO
ALTER SERVER ROLE [bulkadmin] ADD MEMBER [secretadmin]
GO
ALTER LOGIN [secretadmin] ENABLE
GO